version: '3.4'
services:
  sipp_uac:
    image: ctaloi/sipp
    depends_on:
      - sipp_uas
    ports:
      - '5080:5080'
    expose:
      - '5080:5081'
    volumes:
      - ./test/:/test
      - ./scripts/client.sh:/run.sh
    entrypoint: ["/run.sh"]
    networks:
      network:
        ipv4_address: 10.5.3.34

  sipp_uas:
    image: ctaloi/sipp
    ports:
      - '5081:5081'
    expose:
      - '5080:5081'
    volumes:
      - ./test/:/test
      - ./scripts/server.sh:/run.sh
    entrypoint: ["/run.sh"]
    networks:
      network:
        ipv4_address: 10.5.3.35

volumes:
  scenarios:
    driver: local

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.3.32/27
          gateway: 10.5.3.33